# Generated by Django 3.1.2 on 2020-11-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201103_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.FloatField(default=0, verbose_name='星级'),
        ),
    ]
