# Generated by Django 3.1.2 on 2020-11-09 04:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20201109_1226'),
        ('login', '0003_auto_20201106_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='add_time'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default='', verbose_name='review content'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='movie'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='star',
            field=models.FloatField(default=0, verbose_name='star'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(default='Hi!', verbose_name='Personal profile'),
        ),
    ]
