# Generated by Django 3.1.2 on 2020-11-11 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201109_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
