# Generated by Django 3.1.2 on 2020-11-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201102_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(to='movie.Director'),
        ),
    ]
