# Generated by Django 3.1.2 on 2020-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201102_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(related_name='director_movie', to='movie.Director'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['id', 'name'], name='movie_direc_id_6ae9b4_idx'),
        ),
        migrations.AddIndex(
            model_name='director',
            index=models.Index(fields=['id'], name='id_idx'),
        ),
    ]
