# Generated by Django 3.1.2 on 2020-11-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201102_2119'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id', 'name'], name='movie_tag_id_1d1722_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['id'], name='genres_id_idx'),
        ),
    ]
