# Generated by Django 3.1.2 on 2020-11-09 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20201106_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Cast'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comment_nums',
            field=models.IntegerField(default=0, verbose_name='Comment numbers'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Info'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='star',
            field=models.FloatField(default=0, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='genres_name'),
        ),
    ]
